'use strict';
const heroDirections=Array.from({length:6},()=>[]),guardDirections=[],bossDirections=[],newFloors=[];
const heroDirArt=Array.from({length:5},()=>new Image()),guardDirArt=new Image(),bossDirArt=new Image(),itemArt=new Image();
// Runtime atlas decoding keeps original generated sources intact. Flood-fill only
// near-white border-connected pixels; enclosed pale armour remains opaque.
function prepareDirectionAtlas(img,cols,rows,out){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const g=c.getContext('2d');g.drawImage(img,0,0);const im=g.getImageData(0,0,c.width,c.height),d=im.data,w=c.width,h=c.height,seen=new Uint8Array(w*h),queue=new Int32Array(w*h);let head=0,tail=0;
 const pale=i=>{const n=i*4;return d[n+3]<10||(Math.min(d[n],d[n+1],d[n+2])>(img===guardDirArt||img===bossDirArt?185:218)&&Math.max(d[n],d[n+1],d[n+2])-Math.min(d[n],d[n+1],d[n+2])<22)};
 const add=i=>{if(!seen[i]&&pale(i)){seen[i]=1;queue[tail++]=i}};
 for(let x=0;x<w;x++){add(x);add((h-1)*w+x)}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1)}while(head<tail){const i=queue[head++];d[i*4+3]=0;if(i%w)add(i-1);if(i%w<w-1)add(i+1);if(i>=w)add(i-w);if(i<w*(h-1))add(i+w)}g.putImageData(im,0,0);
 const bands=[0];for(let row=1;row<rows;row++){let best=Math.round(row*h/rows),score=Infinity;for(let y=Math.max(bands.at(-1)+20,Math.floor((row-.24)*h/rows));y<Math.min(h,Math.ceil((row+.24)*h/rows));y++){let n=0;for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>90)n++;const q=n+Math.abs(y-row*h/rows)*.001;if(q<score){score=q;best=y}}bands.push(best)}bands.push(h);
 const authored=img===heroDirArt[1]?[0,220,416,610,792,1015,1212,1397,1537]:img===heroDirArt[4]?[0,221,433,635,840,1054,1262,1536]:null;if(authored)bands.splice(0,bands.length,...authored.map(y=>Math.round(y*h/(img===heroDirArt[1]?1537:1536))));

 for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const cuts=img===itemArt?[0,172,384,550,717,868,1088,1266,1422,1588,1774]:null;const sx=cuts?Math.round(cuts[col]*w/1774):Math.floor(col*w/cols),ex=cuts?Math.round(cuts[col+1]*w/1774):Math.floor((col+1)*w/cols),sy=img===itemArt?(col===8?[0,270,516][row]:[0,285,550][row]):bands[row],ey=img===itemArt?(col===8?[270,516,887][row]:[285,550,887][row]):bands[row+1];let l=ex,r=sx,t=ey,b=sy;for(let y=sy;y<ey;y++)for(let x=sx;x<ex;x++)if(d[(y*w+x)*4+3]>90){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}const tile=document.createElement('canvas');tile.width=300;tile.height=480;const tc=tile.getContext('2d'),sw=Math.max(1,r-l+1),sh=Math.max(1,b-t+1),k=Math.min(280/sw,440/sh);tc.drawImage(c,l,t,sw,sh,(300-sw*k)/2,463-sh*k,sw*k,sh*k);cleanSpriteFragments(tile);tile.trim={x:(300-sw*k)/2,y:463-sh*k,w:sw*k,h:sh*k};tile.sourceBounds={x:l,y:t,w:sw,h:sh,bandTop:sy,bandBottom:ey};out.push(tile)}
}
function directionIndex(dx,dy){return (Math.round((Math.atan2(dy,dx)-Math.PI/2)/(Math.PI/4))+8)%8}
function drawDirectionalHero(c,x,y,height,dx,dy){const frames=heroDirections[chosen];if(frames.length!==(chosen===4?28:32))return false;const target=cursorAim(),direction=target?directionIndex(target.dx,target.dy):directionIndex(dx,dy);const mappings=[[0,1,2,5,4,3,6,7],[0,1,2,5,4,3,6,7],[0,1,2,3,4,3,2,1],[0,1,2,3,4,5,6,7],[0,1,2,3,4,3,5,1],[0,1,2,3,4,3,2,1]],row=mappings[chosen][direction],frame=heroMotion?gaitFrameIndex(walkPhase):0,flip=(chosen===2&&direction>=5)||(chosen===4&&(direction===1||direction===3));let tile=frames[row*4+frame];
 // Rarity changes remain visible on moving armour; the full paperdoll uses slot art.
 const key='direction:'+chosen+':'+row+':'+frame+':'+visualSignature();if(movingLooks.has(key))tile=movingLooks.get(key);else{const dressed=document.createElement('canvas');dressed.width=300;dressed.height=480;dressed.trim=tile.trim;const g=dressed.getContext('2d');g.drawImage(tile,0,0);for(const [slot,regions]of Object.entries(bodyRegions)){const tier=wardrobeTier(equipped[slot]);if(!tier)continue;g.save();g.globalCompositeOperation='source-atop';g.globalAlpha=.18;g.fillStyle=tier===2?'#dfb15c':'#6cb4ee';for(const [a,b,w,h]of regions)g.fillRect(a*300,b*480,w*300,h*480);g.restore()}if(movingLooks.size>160)movingLooks.clear();movingLooks.set(key,dressed);tile=dressed}c.save();c.translate(x,y);if(flip)c.scale(-1,1);drawMotionTile(c,tile,0,0,height);c.restore();return true;}
function directionalEnemyTile(f){const rows=f.type===3?bossDirections:guardDirections;if(rows.length!==45)return null;const a=f.facing??Math.atan2(p.y-f.y,p.x-f.x),dir=directionIndex(Math.cos(a),Math.sin(a)),row=[0,1,2,3,4,3,2,1][dir];return {tile:rows[row*9+((f.mapId??routeStage)%9)],flip:dir>0&&dir<4,row}}
function ensureHeroDirections(id){
 const img=heroDirArt[id];
 if(id>=5||!img||!img.complete||heroDirections[id].length)return;
 prepareDirectionAtlas(img,4,id===4?7:8,heroDirections[id]);
}
function initDirectional(){for(let i=0;i<5;i++){heroDirArt[i].onload=()=>{loaded()};heroDirArt[i].onerror=loadError}guardDirArt.onload=()=>{prepareDirectionAtlas(guardDirArt,9,5,guardDirections);loaded()};bossDirArt.onload=()=>{prepareDirectionAtlas(bossDirArt,9,5,bossDirections);loaded()};itemArt.onload=()=>{prepareDirectionAtlas(itemArt,10,3,equipmentFrames);loaded()};guardDirArt.onerror=bossDirArt.onerror=itemArt.onerror=loadError;
 const ember=heroDirArt[0],marrow=heroDirArt[1],rift=heroDirArt[2],frost=heroDirArt[3],monk=heroDirArt[4];ember.src='ember-chimist-directions.png';marrow.src='marrow-gardener-directions.png';rift.src='rift-scribe-directions.png';frost.src='frostbound-warden-directions.png';monk.src='blood-monk-directions.png';guardDirArt.src='regular-enemies-9x5.png';bossDirArt.src='bosses-9x5.png';itemArt.src='equipment-10x3.png';
 const a=new Image(),b=new Image(),c=new Image(),d=new Image(),e=new Image(),f=new Image();newFloors.push(a,b,c,d,e,f);for(const img of newFloors){img.onload=loaded;img.onerror=loadError}a.src='city-customs.png';b.src='city-foundry.png';c.src='city-cathedral.png';d.src='ship-cargo.png';e.src='ship-cryogenic.png';f.src='ship-bridge.png';}
