'use strict';
const gearSlots=[['helmet','頭盔'],['chest','上衣'],['legs','褲甲'],['amulet','頸鏈'],['ring','戒指'],['shoulders','護肩'],['knees','護膝'],['offhand','左手武器'],['weapon','右手武器'],['belt','腰帶']];
const gearNames={helmet:['巡夜兜鍪','凝神面罩','守誓冠冕'],chest:['灰行胸甲','回息法衣','鐘衛重鎧'],legs:['行旅褲甲','疾風綁腿','霜鐵腿甲'],ring:['餘燼指環','回息戒','迅擊印戒'],shoulders:['守望肩甲','鎖鐘護肩','碎影肩衣'],knees:['旅者護膝','踏風護膝','鐵誓膝甲'],belt:['補給腰帶','回息束帶','守門重帶']};
const statNames={hp:'生命',armor:'減傷',speed:'移速',haste:'攻速',regen:'靈息／秒',damage:'傷害',potion:'藥水效果'};
let gearFilter='all',gearDropCounter=0;
// v0.9.0 loot rolls. 0.8.0 picked the variant with lootSerial%3 and used a fixed
// stat table, so every run handed out the identical items in the identical order.
const gearPrefixes=['銹蝕','守夜','餘燼','低語','霜語','血誓','斷鏈','無名','遠行','鐘影','灰紋','裂界'];
const gearSuffixes=['之誓','之痕','之息','之囚','之錨','之歌','之殼','之願'];
const bonusPool={hp:[6,26],armor:[2,7],speed:[3,9],haste:[4,11],regen:[1,3],damage:[3,10],potion:[8,22]};
function rollStats(stats,legendary){
 const out={};
 for(const [k,v] of Object.entries(stats))out[k]=Math.max(1,Math.round(v*(legendary?rnd(1.5,2.5):rnd(.72,1.42))));
 const extras=legendary?(Math.random()<.75?2:1):(Math.random()<.45?1:0);
 const keys=Object.keys(bonusPool);
 for(let i=0;i<extras;i++){const k=keys[Math.floor(rnd(0,keys.length))],[lo,hi]=bonusPool[k];out[k]=(out[k]||0)+Math.round(rnd(lo,hi)*(legendary?1.4:1))}
 return out;
}
function decorateName(base,rarity){
 if(rarity==='common')return base;
 const pre=Math.random()<(rarity==='legendary'?.9:.62)?gearPrefixes[Math.floor(rnd(0,gearPrefixes.length))]:'';
 const suf=Math.random()<(rarity==='legendary'?.7:.3)?gearSuffixes[Math.floor(rnd(0,gearSuffixes.length))]:'';
 return (pre?pre+'的':'')+base+suf;
}
const mouseControl={held:false,id:null,clientX:0,clientY:0,target:null,enemy:null,path:[],clock:0};
function emptyGear(){return Object.fromEntries(gearSlots.map(([s])=>[s,null]))}
function gearStats(){const total={hp:0,armor:0,speed:0,haste:0,regen:0,damage:0,potion:0};for(const item of Object.values(equipped))if(item)for(const [k,v]of Object.entries(item.stats||{}))total[k]=(total[k]||0)+v;return total}
function equipmentHealth(){return gearStats().hp+(equipped.amulet?.effect==='guard'?30:0)}
function weaponWithEffect(effect){return [equipped.weapon,equipped.offhand].find(w=>w?.effect===effect)}
function gearLabel(slot){return gearSlots.find(([s])=>s===slot)?.[1]||slot}
function statsText(stats){return Object.entries(stats||{}).filter(([,v])=>v).map(([k,v])=>`${statNames[k]} +${v}${['armor','speed','haste','damage','potion'].includes(k)?'%':''}`).join(' · ')}
function createEquipment(slot,legendary=false,starter=false){const n=lootSerial++,tier=legendary?2:1,variant=Math.floor(rnd(0,3));let source,stats={};if(slot==='weapon'||slot==='offhand'){source={...weaponSets[chosen][legendary?1:0]};if(slot==='offhand'){source.name='副手 · '+source.name;source.power=Math.round(source.power*.5*rnd(.8,1.3));source.description+='；副手傷害加成減半，同詞綴不疊加'}}else if(slot==='amulet')source={...amuletSets[variant]};else{source={name:gearNames[slot][variant],power:0,effect:null,description:''};const sets={helmet:[{hp:15},{regen:1},{armor:5}],chest:[{hp:25,armor:3},{regen:1,damage:5},{armor:8}],legs:[{hp:12,speed:4},{speed:10},{armor:6}],ring:[{damage:8},{regen:2},{haste:10}],shoulders:[{armor:5},{hp:18},{damage:6}],knees:[{hp:10},{speed:8},{armor:5}],belt:[{potion:20},{regen:1},{hp:20,armor:3}]};stats=rollStats(sets[slot][variant],legendary);source.description=statsText(stats)}if(starter){source.name='舊製 · '+gearLabel(slot);source.power=slot==='weapon'?3:slot==='offhand'?2:0;source.effect=null;stats=slot==='chest'?{hp:12}:slot==='helmet'?{hp:8}:slot==='legs'||slot==='knees'?{speed:2}:slot==='ring'?{damage:2}:slot==='amulet'?{regen:1}:slot==='belt'?{potion:5}:{armor:1};source.description=statsText(stats)}const rarity=starter?'common':legendary?'legendary':'magic';
 if(!starter){
  if(slot==='weapon'||slot==='offhand'){source.power=Math.round(source.power*rnd(.78,1.35));
   // conversion rolls only on legendary weapons; it is the build-defining affix
   if(legendary&&slot==='weapon'&&Math.random()<.45){source.convert=Math.floor(rnd(0,elementNames.length));source.description+='；元素轉換 · '+elementNames[source.convert]}
   stats=rollStats(stats&&Object.keys(stats).length?stats:{damage:4},legendary);source.description=statsText(stats)+(source.description?' · '+source.description:'')}
  else if(slot==='amulet')stats=rollStats({regen:1},legendary);
  source.name=decorateName(source.name,rarity);
 }
 const req=starter?null:rollRequirement(slot,rarity,routeStage);
 return {...source,stats,req,id:++itemSerial,slot,rarity,classId:slot==='weapon'||slot==='offhand'?chosen:null}}
function seedEquipment(){gearDropCounter=0;gearFilter='all';for(const [slot]of gearSlots){const item=createEquipment(slot,false,true);bag.push(item);equipped[slot]=item}p.maxhp+=equipmentHealth();p.hp=p.maxhp;$('#gearbtn').textContent='裝備 · '+bag.length;cancelMouse()}
// BUG-014: the drop slot cycled through a fixed ten-slot wheel and legendaries
// landed every third drop. Both are rolled now, weighted by how deep you are.
function equipmentDrop(x,y){const slots=gearSlots.map(([k])=>k);gearDropCounter++;const legendary=Math.random()<Math.min(.3,.05+routeStage*.022)*(1+runDifficulty*.35);dropGear(x,y,slots[Math.floor(rnd(0,slots.length))],legendary)}
function changeEquipment(id){const item=bag.find(v=>v.id===id);if(!item||!p)return;
 if(!meetsRequirement(item)){toast('屬性不足 · '+requirementText(item));return}const previous=equipped[item.slot];if(previous&&previous.id!==item.id){if(item.grid)previous.grid={...item.grid};else if(!packPlace(previous,carriedItems().filter(i=>i.id!==item.id))){toast('背包冇足夠空間放回現用裝備');return}}delete item.grid;const before=equipmentHealth();equipped[item.slot]=item;p.maxhp+=equipmentHealth()-before;p.hp=Math.min(p.hp,p.maxhp);drawInventory();updateHUD();playSfx('equip',p.x)}
function unequip(slot){if(!p||!equipped[slot])return;if(!packCanUnequip(slot)){toast('背包冇足夠空間卸下');return}const before=equipmentHealth();equipped[slot]=null;p.maxhp+=equipmentHealth()-before;p.hp=Math.min(p.hp,p.maxhp);drawInventory();updateHUD()}
function drawArsenal(){const grid=$('#equipment-slots');grid.replaceChildren();const totals=gearStats();$('#equipment-summary').textContent='生命上限 '+p.maxhp+' · 減傷 '+Math.min(60,Math.round(totals.armor+attrArmor()))+'% · 移速 +'+Math.round(totals.speed+attrSpeed())+'% · 攻速 +'+Math.round(totals.haste+attrHaste())+'%';for(const [slot,label]of gearSlots){const item=equipped[slot],el=document.createElement('div');el.className='equipped-slot';const small=document.createElement('small'),name=document.createElement('b'),detail=document.createElement('p');small.textContent=label;name.textContent=item?.name||'空置';name.style.color=gearColor(item);detail.textContent=describeItem(item);el.append(small,name,detail);if(item){const remove=document.createElement('button');remove.textContent='卸下';remove.onclick=()=>unequip(slot);el.append(remove)}grid.append(el)}const filters=$('#gearfilters');filters.replaceChildren();for(const [slot,label]of [['all','全部'],...gearSlots]){const button=document.createElement('button');button.textContent=label;button.className=gearFilter===slot?'active':'';button.onclick=()=>{gearFilter=slot;drawInventory()};filters.append(button)}$('#bagcount').textContent=bag.length+' / 60';const list=$('#bagitems');list.replaceChildren();for(const item of [...bag].reverse().filter(i=>gearFilter==='all'||i.slot===gearFilter)){const row=document.createElement('div');row.className='gear-item';row.style.setProperty('--rarity',gearColor(item));const desc=document.createElement('div');desc.className='gear-description';const name=document.createElement('b'),detail=document.createElement('p'),compare=document.createElement('p');name.textContent=gearLabel(item.slot)+' · '+item.name;detail.textContent=describeItem(item);const current=equipped[item.slot];compare.className='gear-compare';compare.textContent=current?.id===item.id?'目前裝備':current?'現用：'+current.name+' · '+describeItem(current):'此部位尚未裝備';desc.append(name,detail,compare);const actions=document.createElement('div');actions.className='gear-actions';const use=document.createElement('button');use.textContent=current?.id===item.id?'已裝備':'裝備';use.disabled=current?.id===item.id;use.onclick=()=>equipItem(item.id);actions.append(use);if(!use.disabled){const discard=document.createElement('button');discard.textContent='丟棄';discard.onclick=()=>{bag=bag.filter(i=>i.id!==item.id);$('#gearbtn').textContent='裝備 · '+bag.length;drawInventory()};actions.append(discard)}row.append(desc,actions);list.append(row)}drawPack();setGearPage(gearPage);if(!list.children.length){const empty=document.createElement('p');empty.textContent='暫時未拾獲此部位裝備。';list.append(empty)}}
function gameZoom(){return Math.max(.88,Math.min(1.12,Math.max(W/1500,H/850)))}
function mouseWorld(x,y){const r=canvas.getBoundingClientRect(),zoom=gameZoom();return {x:cam.x+(x-r.left)*W/r.width/zoom,y:cam.y+(y-r.top)*H/r.height/zoom}}
function cancelMouse(){mouseControl.held=false;mouseControl.id=null;mouseControl.target=null;mouseControl.enemy=null;mouseControl.path=[]}
function navPoint(x,y){const q={x,y};confine(q);return Math.hypot(q.x-x,q.y-y)<2}
function planPath(target){const goal={...target};confine(goal);const size=world.w>6000?150:36,cols=Math.ceil(world.w/size),rows=Math.ceil(world.h/size),cell=(x,y)=>Math.floor(y/size)*cols+Math.floor(x/size),pos=i=>({x:(i%cols+.5)*size,y:(Math.floor(i/cols)+.5)*size});if(dist(p,goal)>size*14){const a=Math.atan2(goal.y-p.y,goal.x-p.x),step={x:p.x+Math.cos(a)*size*10,y:p.y+Math.sin(a)*size*10};confine(step);return navPoint(step.x,step.y)?[step,goal]:[goal]}const start=cell(p.x,p.y),end=cell(goal.x,goal.y),cost=new Map([[start,0]]),parent=new Map(),closed=new Set();const heap=[],push=(i,f)=>{heap.push({i,f});let c=heap.length-1;while(c>0){const par=(c-1)>>1;if(heap[par].f<=heap[c].f)break;[heap[par],heap[c]]=[heap[c],heap[par]];c=par}};const pop=()=>{const top=heap[0],last=heap.pop();if(heap.length){heap[0]=last;let c=0;for(;;){const l=c*2+1,r=l+1;let m=c;if(l<heap.length&&heap[l].f<heap[m].f)m=l;if(r<heap.length&&heap[r].f<heap[m].f)m=r;if(m===c)break;[heap[m],heap[c]]=[heap[c],heap[m]];c=m}}return top.i};push(start,0);let found=null;for(let tries=0;heap.length&&tries<4000;tries++){const cur=pop();if(closed.has(cur))continue;if(cur===end||dist(pos(cur),goal)<size){found=cur;break}closed.add(cur);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const x=cur%cols+dx,y=Math.floor(cur/cols)+dy;if(x<0||x>=cols||y<0||y>=rows)continue;const next=y*cols+x,pt=pos(next);if(closed.has(next)||!navPoint(pt.x,pt.y))continue;if(dx&&dy&&(!navPoint(pos(cur).x+dx*size,pos(cur).y)||!navPoint(pos(cur).x,pos(cur).y+dy*size)))continue;const nc=cost.get(cur)+Math.hypot(dx,dy)*size;if(nc<(cost.get(next)??Infinity)){cost.set(next,nc);parent.set(next,cur);push(next,nc+dist(pt,goal))}}}const path=[];if(found!==null){for(let i=found;i!==start&&parent.has(i);i=parent.get(i))path.unshift(pos(i));path.push(goal)}else path.push(goal);return path}
function setMouseGoal(point){mouseControl.target=point;mouseControl.path=planPath(point);mouseControl.clock=.18}
function mouseMovement(dt,manual){if(manual){cancelMouse();return null}mouseControl.clock-=dt;const m=mouseControl;if(m.enemy&&m.enemy.hp<=0){m.enemy=null;m.target=null;m.path=[]}if(m.enemy&&dist(m.enemy,p)<(chosen===4?105:280)){m.path=[];m.target=null;attack();if(!m.held)cancelMouse();return null}if(m.clock<=0){if(m.enemy)setMouseGoal(m.enemy);else if(m.held)setMouseGoal(mouseWorld(m.clientX,m.clientY))}while(m.path.length&&dist(p,m.path[0])<9)m.path.shift();if(!m.path.length){if(!m.held)m.target=null;return null}const next=m.path[0],d=dist(next,p),speed=classes[chosen].speed*movementFactor()*(1+(speedMult-1)*.53)*(1+(gearStats().speed+attrSpeed())/100)*(p.boost>0?1.6:1)*(p.chill>0?.65:1),factor=Math.min(1,d/Math.max(1,speed*dt));return {x:(next.x-p.x)/d*factor,y:(next.y-p.y)/d*factor}}
function initMouse(){canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||mode!=='play')return;e.preventDefault();const at=mouseWorld(e.clientX,e.clientY);if(e.button===2){const a=Math.atan2(at.y-p.y,at.x-p.x);skill({...at,dx:Math.cos(a),dy:Math.sin(a)});return}if(e.button!==0)return;cancelMouse();mouseControl.id=e.pointerId;mouseControl.clientX=e.clientX;mouseControl.clientY=e.clientY;mouseControl.held=true;canvas.setPointerCapture(e.pointerId);mouseControl.enemy=foes.filter(f=>f.hp>0).find(f=>Math.hypot(at.x-f.x,(at.y-(f.y-35))*.7)<Math.max(35,f.r));setMouseGoal(mouseControl.enemy||at);ring(at.x,at.y,'#dec083',24,.4)});canvas.addEventListener('pointermove',e=>{if(e.pointerId===mouseControl.id){mouseControl.clientX=e.clientX;mouseControl.clientY=e.clientY}});canvas.addEventListener('pointerup',e=>{if(e.pointerId!==mouseControl.id)return;mouseControl.held=false;mouseControl.id=null;
 // Releasing ends the pursuit. Holding still chases and keeps attacking.
 if(mouseControl.enemy&&dist(mouseControl.enemy,p)>=(chosen===4?105:280))cancelMouse();});canvas.addEventListener('pointercancel',cancelMouse);addEventListener('blur',cancelMouse)}
