'use strict';
// Fifth playable class. IDs 0–3 remain stable for existing saves.
const bloodMonkClass={name:'血饕僧',en:'BLOODFEAST MONK',color:'#dc827e',desc:'披血衣，誦餓咒，以巨腹承萬厄。',tag:'近戰 · 吞噬與血咒',note:'吞噬回復生命並累積飽食；腹震消耗飽食增傷，血咒以生命換取範圍壓制。',skill:'饕口噬',hp:195,speed:155,rate:.65,damage:43};
const monkArt=new Image(),monkLogoArt=new Image(),monkFrames=[];
let monkReady=false,monkLogosReady=false;
skillTrees.push([
 {name:'饕口噬',role:'吞噬',cost:22,cd:5,nodes:[['饕口噬','吞噬近身敵人，造成 76 基礎傷害；每命中回復 7 生命，最多 3 次，累積飽食。'],['啖骨經','吞噬範圍擴大，傷害 +30%；每命中回復 10 生命。'],['無底饕口','傷害 +60%；每命中回復 13 生命，最多 3 次。']]},
 {name:'腹雷震',role:'腹震',cost:26,cd:8,nodes:[['腹雷震','向前衝撞再震退近敵。消耗全部飽食，每點增加 0.7 基礎傷害。'],['千斤墜','震波範圍擴大，傷害 +30%，擊退距離增加。'],['崩城巨腹','傷害 +60%；延遲引發第二道半傷害震波。']]},
 {name:'血衣咒',role:'血咒',cost:20,cd:10,nodes:[['血衣咒','消耗 12% 最大生命，建立 4 秒咒域，每秒傷害並減速敵人。'],['飲血禪','咒域擴大，持續 5 秒；每次命中回復 2 生命。'],['餓佛降世','咒域持續 6 秒；每次命中回復 3 生命，傷害 +60%。']]}
]);
weaponSets.push([{name:'噬齒鐵杵',effect:'glutton',description:'近戰普攻命中回復 2 生命，每次攻擊最多 6',power:12},{name:'餓佛鎮魂杵',effect:'glutton',description:'近戰普攻命中回復 4 生命，每次攻擊最多 12',power:24}]);
function prepareMonk(){const sheet=document.createElement('canvas');sheet.width=monkArt.naturalWidth;sheet.height=monkArt.naturalHeight;const c=sheet.getContext('2d');c.drawImage(monkArt,0,0);const im=c.getImageData(0,0,sheet.width,sheet.height),d=im.data;for(let i=0;i<d.length;i+=4){const v=Math.max(d[i],d[i+1],d[i+2]);if(v<24)d[i+3]=0;else if(v<40)d[i+3]=Math.round((v-24)/16*255)}c.putImageData(im,0,0);for(let i=0;i<3;i++){const t=document.createElement('canvas');t.width=300;t.height=480;t.getContext('2d').drawImage(sheet,i*sheet.width/3,0,sheet.width/3,sheet.height,0,0,300,480);monkFrames.push(t)}monkReady=true;lookCache.clear()}
function wardrobeFrame(tier,id=chosen){return id===4?monkFrames[tier]:id===5?angelFrames[tier]:wardrobeFrames[tier*4+id]}
function monkStrike(angle){const hits=foes.filter(f=>f.hp>0&&dist(p,f)<125&&Math.cos(Math.atan2(f.y-p.y,f.x-p.x)-angle)>.05);for(const f of hits)hit(f,bloodMonkClass.damage*gearPower(),4);const w=weaponWithEffect('glutton');if(w)p.hp=Math.min(p.maxhp,p.hp+Math.min(3,hits.length)*(w.rarity==='legendary'?4:2));p.satiety=Math.min(100,(p.satiety||0)+hits.length*3);addVFX(4,p.x+p.dx*60,p.y+p.dy*60,105,.42);ring(p.x,p.y,bloodMonkClass.color,110,.35);playSfx('attack',p.x,4)}
function monkCastAllowed(){if(chosen!==4||activeSkill!==2)return true;if(p.hp<=Math.ceil(p.maxhp*.12)){toast('生命不足以施展血衣咒');return false}return true}
function releaseMonk(c){const r=c.rank,power=gearPower()*(1+(r-1)*.3);if(c.branch===0){const targets=foes.filter(f=>f.hp>0&&dist(p,f)<105+r*15);burstAt(p.x,p.y,105+r*15,76*power,4);p.hp=Math.min(p.maxhp,p.hp+Math.min(3,targets.length)*(4+r*3));p.satiety=Math.min(100,(p.satiety||0)+targets.length*12);sparks(p.x,p.y,'#bd555e',24,160)}else if(c.branch===1){cancelMouse();p.x+=c.dx*105;p.y+=c.dy*105;confine(p);p.inv=.7;const food=p.satiety||0;p.satiety=0;const radius=125+r*20,damage=(65+food*.7)*power;burstAt(p.x,p.y,radius,damage,4);for(const f of foes)if(f.hp>0&&dist(p,f)<radius){const a=Math.atan2(f.y-p.y,f.x-p.x);f.x+=Math.cos(a)*(35+r*15);f.y+=Math.sin(a)*(35+r*15);confine(f)}if(r===3)castFields.push({kind:'meteor',x:p.x,y:p.y,r:radius,delay:.55,life:1,damage:damage*.5,element:4});shake=9}else{castFields.push({kind:'blood',x:c.x,y:c.y,r:100+r*20,life:3+r,tick:0,damage:23*power,element:4,rank:r});ring(c.x,c.y,'#bb586c',100+r*20,1)}}
function updateMonkFields(dt){for(const z of castFields)if(z.kind==='blood'){z.tick-=dt;if(z.tick<=0){z.tick=1;let count=0;for(const f of foes)if(f.hp>0&&dist(z,f)<z.r){hit(f,z.damage,4);f.slow=2;count++}if(z.rank>1)p.hp=Math.min(p.maxhp,p.hp+count*z.rank);addVFX(4,z.x,z.y,z.r*1.3,.7)}}}
function monkHUD(){const e=$('#satiety');e.hidden=chosen!==4;if(chosen===4)e.textContent='飽食 '+Math.floor(p.satiety||0)+' / 100'}
